---
- name: Stop conflicting services if they exist
  ansible.builtin.shell: |
    if systemctl list-unit-files | grep -q "^{{ item }}.service"; then
      systemctl stop {{ item }}
      systemctl disable {{ item }}
    fi
  loop:
    - httpd
    - nginx
  args:
    executable: /bin/bash

- name: Install HAProxy
  ansible.builtin.yum:
    name: haproxy
    state: present

- name: Deploy HAProxy configuration
  ansible.builtin.template:
    src: haproxy.cfg.j2
    dest: /etc/haproxy/haproxy.cfg
    owner: root
    group: root
    mode: '0644'

- name: Validate HAProxy configuration
  ansible.builtin.command: haproxy -c -f /etc/haproxy/haproxy.cfg

- name: Enable and start HAProxy
  ansible.builtin.systemd:
    name: haproxy
    state: started
    enabled: yes
