---
- name: Install MariaDB server
  yum:
    name: mariadb-server
    state: present

- name: Start and enable MariaDB
  systemd:
    name: mariadb
    state: started
    enabled: yes

- name: Copy MariaDB client config
  template:
    src: my.cnf.j2
    dest: /root/.my.cnf
    owner: root
    group: root
    mode: '0600'

- name: Ensure root password is set
  mysql_user:
    name: root
    host: localhost
    password: "{{ db_root_password }}"
    login_unix_socket: /var/lib/mysql/mysql.sock
    check_implicit_admin: yes
    state: present

- name: Remove anonymous users
  mysql_user:
    name: ''
    host_all: yes
    state: absent
    login_user: root
    login_password: "{{ db_root_password }}"

- name: Remove test database
  mysql_db:
    name: test
    state: absent
    login_user: root
    login_password: "{{ db_root_password }}"

- name: Reload privileges
  command: mysqladmin flush-privileges

# ---------------------------------------------------
# Install Apache + PHP + phpMyAdmin
# ---------------------------------------------------
- name: Install required packages for phpMyAdmin
  yum:
    name:
      - httpd
      - php
      - php-mysqlnd
      - php-fpm
      - php-json
      - php-mbstring
      - phpmyadmin
    state: present

- name: Ensure correct phpMyAdmin Apache config
  copy:
    dest: /etc/httpd/conf.d/phpMyAdmin.conf
    content: |
      Alias /phpMyAdmin /usr/share/phpMyAdmin
      <Directory /usr/share/phpMyAdmin/>
          AddDefaultCharset UTF-8
          DirectoryIndex index.php
          Require all granted
      </Directory>
  notify: Restart Apache
  
- name: Allow phpMyAdmin for all hosts
  lineinfile:
    path: /etc/httpd/conf.d/phpMyAdmin.conf
    regexp: 'Require ip'
    line: '    Require all granted'
  notify: restart_apache

- name: Ensure Apache is installed
  package:
    name: httpd
    state: present
  notify: Restart Apache safely

- name: Fix phpMyAdmin Apache configuration for Apache 2.4+
  ansible.builtin.lineinfile:
    path: /etc/httpd/conf.d/phpMyAdmin.conf
    state: present
    regexp: '^\s*Require all granted'
    line: '    Require all granted'
  notify:
    - Restart Apache safely

- import_tasks: phpmyadmin.yml

- name: Ensure phpMyAdmin is installed
  dnf:
    name: phpMyAdmin
    state: present
  become: yes

- name: Backup existing phpMyAdmin Apache config if exists
  copy:
    src: /etc/httpd/conf.d/phpMyAdmin.conf
    dest: /etc/httpd/conf.d/phpMyAdmin.conf.bak
    remote_src: yes
  ignore_errors: yes
  become: yes

- name: Deploy correct phpMyAdmin Apache config
  copy:
    dest: /etc/httpd/conf.d/phpMyAdmin.conf
    content: |
      Alias /phpMyAdmin /usr/share/phpMyAdmin

      <Directory /usr/share/phpMyAdmin/>
          AddDefaultCharset UTF-8
          DirectoryIndex index.php
          Require all granted
      </Directory>
  notify: Restart Apache
  become: yes

- name: Ensure Apache can read phpMyAdmin files under SELinux
  command: setsebool -P httpd_read_user_content 1
  become: yes

- name: Set correct SELinux context for phpMyAdmin
  command: chcon -R -t httpd_sys_content_t /usr/share/phpMyAdmin
  become: yes

 
