---
nagios_version: "4.5.9"
nagios_admin_user: nagiosadmin
nagios_admin_pass: "Nagios123"
nagios_source_url: "https://github.com/NagiosEnterprises/nagioscore/archive/nagios-{{ nagios_version }}.tar.gz"
